import { useNavigate } from 'react-router-dom';
import { useCreateRobot, initialRobotForm } from './useCreateRobot';
import { useAuth } from './auth';
import { createRobot as createRobotPublic } from '../api/index';
import { createRobot as createRobotPrivate } from '../api/createRobot';

export const CreateRobot = () => {
  const navigate = useNavigate();
  const auth = useAuth();

  const [robotInput, setRobotInput] = useCreateRobot(initialRobotForm);

  const handleCreateRobot = async () => {
    if (auth.currentAuthUsername) {
      const robotRequest = {
        ...robotInput,
        createdBy: auth.currentAuthUsername,
      };
      const createdRobot = await createRobotPrivate(robotRequest);
      console.log(`handleCreateRobotPrivate`, createdRobot);
    } else {
      const robotRequest = {
        ...robotInput,
      };
      const createdRobot = await createRobotPublic(robotRequest);
      console.log(`handleCreateRobotPublic`, createdRobot);
    }
    navigate('/');
  };

  /*
    Tabs:
    Basic Info: first name, last name, maiden name, email, password, birthdate, age, phone, university
    Appearance: Image, blood group, eye color, hair, height, weight
    Location: Address
    Financial: Bank
    Occupation: Company
    Misc:  Mac Address, ein, userAgent, domain

      Basic Info Tab is mandatory user-input
    Other tabs are pre-generated by default (check box to toggle beteween pre-generated and user-generated)
    */

  return (
    <div>
      <label>
        Username:{' '}
        <input type="text" name="usernameInput" onChange={setRobotInput} />
      </label>
      <label>
        Email: <input type="text" name="emailInput" onChange={setRobotInput} />
      </label>
      <label>
        Password:{' '}
        <input type="text" name="passwordInput" onChange={setRobotInput} />
        <button type="button" onClick={handleCreateRobot}>
          Create Robot
        </button>
      </label>
    </div>
  );
};
