import { useState } from 'react';

export const useCreateRobot = (initialInput) => {
  const [loginInput, setLoginInput] = useState({ initialInput });

  return [
    loginInput,
    (e) => {
      setLoginInput({ ...loginInput, [e.target.name]: e.target.value });
    },
  ];
};

export const robotFormBasic = {
  firstName: '',
  lastName: '',
  password: '',
  maidenName: '',
  email: '',
  birthdate: '',
  age: '',
  phone: '',
  univeristy: '',
};

export const robotFormAppearance = {
  image: '',
  bloodGroup: '',
  eyeColor: '',
  hair: { color: '', type: '' },
  height: '',
  weight: '',
};

export const robotFormLocation = {
  address: '',
  city: '',
  postalCode: '',
  state: '',
  coordinates: { lat: '', lng: '' },
};

export const robotFormFinancial = {
  cardExpire: '',
  cardNumber: '',
  cardType: '',
  currentcy: '',
  iban: '',
};

export const robotFormMisc = {
  macAddress: '',
  ein: '',
  userAgent: '',
  domain: '',
};

export const initialRobotForm = {
  robotFormBasic,
  robotFormAppearance,
  robotFormLocation,
  robotFormFinancial,
  robotFormMisc,
};

/*
Tabs:
Basic Info: first name, last name, maiden name, email, password, birthdate, age, phone, university
Appearance: Image, blood group, eye color, hair, height, weight
Location: Address
Financial: Bank
Occupation: Company
Misc:  Mac Address, ein, userAgent, domain

    Basic Info Tab is mandatory user-input
Other tabs are pre-generated by default (check box to toggle beteween pre-generated and user-generated)
*/

export default { useCreateRobot, initialRobotForm };
